### PR TITLE
Updated BaseQuery class

### PR DESCRIPTION
**Pull request by jedi2light**
Rewritten  filter() method which now provides DjangoORM-like filter construction and syntax. At the same time allows use native LDAP query syntax.
Signature: filter(legacy, **kwargs)
Returns: BaseQuery
Usage: entry_instance_list = EntryClass.query.filter(attr1[__filter]=value1, ...).all()

### CODE REVIEW

**Comment by jagheterfredrik** [comment]
This syntax looks horrible, I might suggest something more along the lines of SQLAlchemy.

**Comment by jedi2light** [comment]
Well, it would be great... How soon?

**Comment by jagheterfredrik** [comment]
Oh, I'm sorry, I do not have time to implement it. I would suggest you fork this repo and simply make the changes yourself.

**Comment by jedi2light** [comment]
Well, forked already )

**Pull request closed without merging**
